services:
  web:
    container_name: nuxt
    depends_on:
      - db
    build: .
    env_file: .env.example
    ports:
      - "3000:3000"

  db:
    container_name: postgres
    image: postgres:18
    restart: always
    env_file: .env.example
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file: .env.example
    ports:
      - "5050:80"

volumes:
  db:
    driver: local