services:
  web:
    container_name: nuxt
    build: .
    env_file: .env.example
    ports:
      - "3000:3000"

  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file: .env.example
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file: .env.example
    ports:
      - "5050:80"